name: Run Tests on Pull Request

on:
  # Trigger the workflow when a Pull Request is opened or synchronized targeting the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  test:
    # Specify the self-hosted runner with the appropriate tags
    runs-on: self-hosted
    tags: 
      - Linux
      - X64
      - ChainAlchemy
      - Python

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies (from requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Run tests using pytest
    - name: Run tests
      run: |
        pytest
